apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: backend-monitor
    release:  monitoring
  name: backend-monitor
  namespace:  monitoring

spec:
  jobLabel: job
  endpoints:
    - interval: 2s
      port: http
      path: /metrics
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - memories-notes-app-namespace