apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret-smtp
  namespace: argocd
type: Opaque
stringData:
  email-username: "prakashghorpade2001@gmail.com"
  email-password: "yhwgniyorcvitpmp"
  email-host: "smtp.gamil.com"
  email-port: "465"

# This secrets used by argocd Notifications