kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: memories-notes-app-namespace
spec:
  capacity:
    storage: 1Gi
  
  accessModes:
    - ReadWriteOnce

  storageClassName: manual
  
  persistentVolumeReclaimPolicy:  Retain

  hostPath:
    path: /mnt/mongodb-data

