apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: memories-notes-image-updater
  namespace: argocd

spec:

  # Default update strategy
  commonUpdateSettings:
    updateStrategy: semver

  # Git write-back
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"

    gitConfig:
      repository: "https://github.com/prakashghropade/Memories-a-note-app.git"
      branch: "main"
      writeBackTarget: "kustomization"

  # Applications to monitor
  applicationRefs:

    # Frontend
    - namePattern: "frontend-app"

      images:
        - alias: "frontend"
          imageName: "prakashghorpade2001/memories-notes-app-frontend:1.0.0"

          commonUpdateSettings:
            updateStrategy: semver

    # Backend
    - namePattern: "backend-app"

      images:
        - alias: "backend"
          imageName: "prakashghorpade2001/memories-notes-app-backend:1.0.0"

          commonUpdateSettings:
            updateStrategy: semver