apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: memories-notes-image-updater
  namespace: argocd

spec:

  commonUpdateSettings:
    updateStrategy: semver

  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"

    gitConfig:
      repository: "https://github.com/prakashghropade/Memories-a-note-app.git"
      branch: main
      writeBackTarget: kustomization

  applicationRefs:

    - namePattern: frontend-app

      images:
        - alias: frontend
          imageName: prakashghorpade2001/memories-notes-app-frontend
          commonUpdateSettings:
            updateStrategy: semver

    - namePattern: backend-app

      images:
        - alias: backend
          imageName: prakashghorpade2001/memories-notes-app-backend
          commonUpdateSettings:
            updateStrategy: semver