apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memories-notes-dev

resources:
  - ../../base

images:
  - name: prakashghorpade2001/memories-notes-app-backend
    newName: prakashghorpade2001/memories-notes-app-backend
    newTag: v1.0.74

patches:
  - path: backend-patch.yaml

  - target:
      kind: Ingress
      name: memories-notes-ingress-backend
    path: ingress-patch.yaml