apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.email: "prakashghorpade901@gmail.com"
    notifications.argoproj.io/subscribe.on-deployed.email: "prakashghorpade901@gmail.com"
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: "prakashghorpade901@gmail.com"

spec:
  project: memories-notes-app-project
  source:
    repoURL: https://github.com/prakashghropade/Memories-a-note-app.git
    targetRevision: main
    path: k8s_configuration/backend/overlays/stagging
  destination:
    server: https://kubernetes.default.svc
    namespace: memories-notes-stag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m