kind: Deployment
apiVersion: apps/v1
metadata:
  name: backnd-deployment
  namespace: memories-notes-app-namespace
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      
      initContainers:
        - name: wait-for-mongodb
          image: mongo:8.0.4
          command:
            - sh
            -  -c
            - |
              until mongosh "mongodb://admin:admin123@mongodb-service:27017/admin" --authenticationDatabase admin --eval 'db.adminCommand("ping")' --quiet; do
                echo "Waiting for MongoDB..."
                sleep 5
              done
              echo "MongoDB is ready"

      containers:
      - name: backend
        image: prakashghorpade2001/memories-notes-app-backend:v1.0.71
        ports:
        - containerPort: 3001
 
        envFrom:
        - configMapRef:
            name: backend-config

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        startupProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

