apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: memories-notes-app-namespace
data:
  REACT_APP_EMAILJS_PUBLIC_KEY: "UXdhGRHUpXExHDUQm"
  REACT_APP_EMAILJS_SERVICE_ID: "service_2w1v46i"
  REACT_APP_EMAILJS_TEMPLATE_ID: "template_cvmh8kr"
  REACT_APP_API_URL: "http://43.205.116.80/:30002/"