apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: prakashghorpade2001/memories-notes-app-frontend
    newTag: v1.0.41
