apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-dev
  annotations: 
  argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 1Gi

  hostPath:
    path: /mnt/data/mongodb-dev