kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: memories-notes-app-namespace
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 3Gi
  
  accessModes:
    - ReadWriteOnce

  storageClassName: "manual"
  
  persistentVolumeReclaimPolicy:  Retain

  hostPath:
    path: /mnt/mongodb-data

