apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  
  storageClassName: "manual"
  volumeName: mongodb-pv-stag

  resources:
    requests:
      storage: 1Gi