name: Frontend CI

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Enter docker image tag"
        required: true
        default: ""
        type: string
      
      backend_url:
        description: "Enter the  backend url"
        required: true
        default: ""
        type: string
env:
  IMAGE_NAME: prakashghorpade2001/memories-notes-app-frontend:${{ inputs.image_tag }}

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build frontend Image
        run: |
          docker build \
              --build-arg REACT_APP_API_URL=${{ inputs.backend_url }} \
          -t ${{ env.IMAGE_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Frontend Image
        run: |
          docker push \
          ${{ env.IMAGE_NAME }}

      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Terraform Deployment Successful"
          to: ${{ secrets.MAIL_TO }}
          from: Github Actions
          body: |
            Frontend image build and push to dockerhub successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Frontend Image build and pushed : SUCCESS
      
      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Terraform Deployment Failed"
          to: ${{ secrets.MAIL_TO }}
          from: Github Actions
          body: |
            Frontend image build and push to dockerhub has FAILED.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Frontend Image build and pushed: FAILED
            Check the GitHub Actions run: 
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}    




    